/**
 * Promo Code Verifier
 * This program is used to verify the Promo codes
 * generated by another program.
 * It reads the 5 letters and then checks the final
 * letter based on a specific formula to verify the codes authenticity.
 * 
 * 
 * @author (Zac Fawcett) 
 * @version (June 23rd 2021)
 */
// Standard import for the Scanner class
import java.util.*;
public class VerifyPromoCode {
    public static void main (String [] args) {
        // Create a Scanner object attached to the keyboard
        Scanner in = new Scanner (System.in);
        // Prompt user to enter the 5 letter promo code
        System.out.print("Enter the promo code to verify: ");
        String temp = in.nextLine();
        if (temp.length() != 5){
            // Invalid promo if wrong number of letters
            System.out.println ("Invalid promo code, should be 5 letters");

        }
        else {
            // Convert input to all Uppercase in case user enters any lowercase letters
            String promo = temp.toUpperCase();             

            // Read string letters to individual characters
            char c1 = promo.charAt(0); 
            char c2 = promo.charAt(1);
            char c3 = promo.charAt(2);
            char c4 = promo.charAt(3);
            char c5 = promo.charAt(4);

            // calculate sum of 1st character + 2 * 2nd character 
            //+ 3rd character + 2 * 4th character
            int sum = (c1 + c2*2 + c3 + c4*2);

            // figure out the remainder
            char check = (char)(sum % 26);

            // add the remainder to the UNICODE for 'A' to come up 
            // with the check digit
            check += 'A';

            if (c5 == check) {
                // Alerts user of valid promo code
                System.out.printf ("This is a valid promo code"); 
            } else if (c1 < 65 || c2 < 65 || c3 < 65 || c4 < 65 || c5 < 65) {
                // Error checking for non alphabet characters
                System.out.println("Letters only. Restart program and try again."); 
            } else if (c1 > 91 || c2 > 91 || c3 > 91 || c4 > 91 || c5 > 91){
                // Error checking for non alphabet characters    
                System.out.println("Letters only. Restart program and try again."); 
            } else 
            // Message for incorrect promo code and Gives user the expected check letter    
                System.out.printf("Invalid promo code, check digit should have been %c", check); 

        }
    }
}
